import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Sidebar from "@/components/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-backgroundPrimary`}
      >
        <div className="flex flex-row sm:gap-2">
          <div className="sm:w-full sm:max-w-[18rem]">
            <input
              type="checkbox"
              id="sidebar-mobile-fixed"
              className="sidebar-state"
            />
            <label
              htmlFor="sidebar-mobile-fixed"
              className="sidebar-overlay"
            ></label>
            <Sidebar />
          </div>
          <div className="flex w-full flex-col p-4">
            <div className="w-fit">
              <label
                htmlFor="sidebar-mobile-fixed"
                className="btn-primary btn sm:hidden"
              >
                Open Sidebar
              </label>
            </div>

            <StoreProvider>{children}</StoreProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
